
import Sidebar from "@/components/dashboard/layouts/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Brand Cosmo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-[#f8f8f8] flex">
      <div className="w-[18%]">
        <Sidebar />
      </div>
      <div className="w-[82%] p-10">{children}</div>
    </div>
  );
}
